const { Exercises } = require('../models');

const exerciseData = [
    {
        exercise_name: 'Dumb Bell Press',
        description: 'Hold two dumbbells with palms facing forward and your thumbs wrapped around the handle. On an inhale, lower the dumbbells slightly wider than your mid-chest, slowly and with control. Gently touch the dumbbells to your chest. On an exhale, press your arms upwards, keeping your elbows slightly bent ',
        sets: 4,
        reps: 12,
        musclegroup_id: 1,
    },
    {
        exercise_name: 'Push-Ups',
        description: 'Simply position your hands under your shoulders and put your toes on the floor, you should now be in a plank position. Lower your chest to the floor by bending your elbows without letting your hips drop then push back up to start position.',
        sets: 4,
        reps: 12,
        musclegroup_id: 1,
        // image_id: ,
    },
    {
        exercise_name: 'Machine Chest Flys',
        description: 'Align the machine so that the handles are positioned right under your shoulders. You should be able to put your arms straight out to the side and grab the handle, Find a weight that will make you reach muscle failure at around 12 reps, Puff your chest out and make sure youre sitting up straight',
        sets: 4,
        reps: 12,
        musclegroup_id: 1,
        // image_id: ,
    },
    {
        exercise_name: 'medicine ball chest press',
        description: ' Lie flat on your back on a mat with your knees bent and your feet flat on the ground. Hold a medicine ball with both hands at chest level, keeping your elbows close to your body.Inhale deeply, then exhale as you push the medicine ball away from your chest, extending your arms fully. Your elbows should be slightly bent at the top of the movement to avoid locking out your joints.Inhale again as you slowly lower the medicine ball back to your chest, keeping your elbows close to your body.Repeat for the desired number of reps. ',
        sets: 4,
        reps:12,
        musclegroup_id: 1,
        // image_id: ,
    },
    {
        exercise_name: 'Lat Pulldown',
        description: 'While seated, you pull a hanging bar, downwards, toward you to reach chin level; then release it back up with control for one repetition.',
        sets: 4,
        reps: 12,
        musclegroup_id: 2,
        // image_id: ,
    },
    {
        exercise_name: 'Reverse Fly',
        description: 'Standing or sitting, you will tilt your torso to a 45 degree angle with hinge at your hips, allow your arms to hang down the side of your body. Pull the dumbbells towards the ceiling using the rear delts and lower back down to starting positon.',
        sets: 4,
        reps: 12,
        musclegroup_id: 2,
        // image_id: ,
    },
    {
        exercise_name: 'Close Grip Seated Row',
        description: 'Start by sitting on vertical row machine, grabbing handle bars with neutral grip. Once in position, slowly pull the handles in towards your sides, squeezing your back and lat muscles, and hold for a count then back to start position. ',
        sets: 4,
        reps: 12,
        musclegroup_id: 2,
        // image_id: ,
    },
    {
        exercise_name: 'Supermans',
        description: 'Lying on stomach, extend hands in front of head. Keeping head in a neutral position, looking toward floor, lift both arms and legs up toward the ceiling. Feel as if youre reaching far away from your body with hands and feet, hold this position for 3 seconds then lower back to ground. ',
        sets: 4,
        reps: 12,
        musclegroup_id:2,
        // image_id: ,
    },
    {
        exercise_name: ' Back Squats',
        description: 'Sit back into hips and keep the back straight and the chest up, squatting down so the hips are below the knees. From the bottom of the squat, press feet into the ground and push hips forward to return to the top of the standing position. Can be done with or without weights, squat rack, or Smith Machine. ',
        sets: 4,
        reps: 12,
        musclegroup_id: 3,
        // image_id: ,
    },
    {
        exercise_name: 'Leg Extension',
        description: ' Sit on leg extension machine with a weighted pad on top of your lower legs. Then you use your quads to repeatedly extend your knees and lift your lower legs. ',
        sets: 4,
        reps: 12,
        musclegroup_id: 3,
        // image_id: ,
    },
    {
        exercise_name: 'RDLs',  
        description: 'Assume a stance that is roughly shoulder-width with your toes pointed forward. You will then want to brace your core and hinge at your hips (not spine). Try to get butt to wall behind you, with slight bend at your knees. Once you feel a stretch in the hamstrings you want to push your hips forward engaging the glutes to upright position. Can be done with barbell, dumbbell, or cable machine.',
        sets: 4,
        reps: 12,
        musclegroup_id: 3,
        // image_id: ,
    },
    {
        exercise_name: 'Lunges',
        description: 'Stand with your feet hip-width apart. Step forward and bend both knees, lowering until your knees are bent at a 90-degree angle. Shift forward onto the lead leg. Push off on both legs and step through, lifting your back leg and bringing it forward so your rear foot lands ahead of you in a lunge position.  Can be done with or without weights. ',
        sets: 4,
        reps: 12,
        musclegroup_id:3,
        // image_id: ,
    },
    {
        exercise_name: 'Dumbbell Shoulder Press',
        description: 'Sitting, hold a dumbbell in each hand, and raise both weights to shoulder level with palms facing out and elbows bent. Press the weights up and toward each other as you straighten your arms. At the top of the movement, keep a slight bend in your elbows. Slowly bring down the weights, and return to the starting position. ',
        sets: 4,
        reps: 12,
        musclegroup_id: 5,
        // image_id: ,
    },
    {
        exercise_name: 'Standing Dumbbell Fly',
        description: 'Hold a dumbbell in each hand by  your sides. Without shrugging, use your   upper body to swing the weights up a few inches. Your arms and torso will form an upside down V shape.',
        sets: 4,
        reps: 12,
        musclegroup_id: 5,
        // image_id: ,
    },
    {
        exercise_name: 'Dumbbell Front Raises',
        description: 'standing hip with apart with a dumbbell in each hand, bring the arms up in front of the body to eye level with slight bend in the elbow, lower back down to body.',
        sets: 4,
        reps: 12,
        musclegroup_id: 5,
        // image_id: ,
    },
    {
        exercise_name: 'Band Pull Aparts',
        description: 'Stand with your feet shoulder-width apart, holding a resistance band with both hands. Your palms should be facing down and your hands should be positioned slightly wider than shoulder-width apart. Keeping your arms straight, pull the band apart by moving your hands out to the sides and bringing your shoulder blades together. Make sure to keep your arms parallel to the floor throughout the movement.Pause briefly at the end of the movement, then slowly release the tension on the band by bringing your hands back together in front of your chest.Repeat for the desired number of reps.',
        sets: 4,
        reps: 12,
        musclegroup_id: 5,
        // image_id: ,
    },
    {
        exercise_name: ' Skull Crushers',
        description: ' Lie flat on a bench with your feet on the ground. Hold a dumbbell in each hand with your palms facing each other and your arms extended straight up towards the ceiling. Slowly bend your elbows, lowering the dumbbells down towards your forehead. Keep your upper arms stationary and your elbows pointed straight up throughout the movement. Pause briefly at the bottom of the movement, then slowly extend your arms back up to the starting position, making sure to keep your elbows pointed straight up. Repeat for the desired number of reps.',
        sets: 4,
        reps: 12,
        musclegroup_id: 4,
        // image_id: ,
    },
    {
        exercise_name: 'Cable Tricep Pushdown',
        description: ' Stand facing a cable machine with your feet shoulder-width apart. Hold the cable attachment with both hands, palms facing down, and bring your hands up to shoulder level. Keep your elbows tucked in close to your sides, and slowly extend your arms down towards your thighs. Keep your upper arms stationary and your elbows pointed straight down throughout the movement. Pause briefly at the bottom of the movement, then slowly bring your hands back up to shoulder level, making sure to keep your elbows tucked in close to your sides. Repeat for the desired number of reps.',
        sets: 4,
        reps: 12,
        musclegroup_id: 4,
        // image_id: ,
    },
    {
        exercise_name: 'DB Hammer Curls',
        description: ' Stand with your feet shoulder-width apart, holding a dumbbell in each hand with your palms facing in towards your body. Keep your elbows tucked in close to your sides, and slowly curl the dumbbells up towards your shoulders, keeping your palms facing in towards your body throughout the movement. Pause briefly at the top of the movement, then slowly lower the dumbbells back down to the starting position, keeping your palms facing in towards your body. Repeat for the desired number of reps.',
        sets: 4,
        reps: 12,
        musclegroup_id: 4,
        // image_id: ,
    },
    {
        exercise_name: 'ForeArm Curls',
        description: 'Sit on a bench or chair with your feet flat on the floor, holding a dumbbell in one hand with your palm facing up. Rest your forearm on a bench or table so that your hand is hanging off the edge, with your wrist in a neutral position. Slowly curl the dumbbell up towards your forearm, keeping your wrist straight and your forearm stationary throughout the movement.Pause briefly at the top of the movement, then slowly lower the dumbbell back down to the starting position.Repeat for the desired number of reps, then switch arms and repeat. ',
        sets: 4,
        reps: 12,
        musclegroup_id: 4,
        // image_id: ,
    },
    {
        exercise_name: ' Jumping Jacks',
        description: ' Stand with your feet together and your arms by your sides. Jump up and spread your feet shoulder-width apart, while simultaneously raising your arms out to the sides and overhead. Jump back to the starting position with your feet together and your arms by your sides.Repeat the movement for the desired number of sets. For each set do 30-45 seconds.',
        sets: 2,
        reps: 0,
        musclegroup_id: 6,
        // image_id: ,
    },
    {
        exercise_name: 'High Knees',
        description: ' Stand with your feet shoulder-width apart and your arms by your sides. Start jogging in place, lifting your knees up towards your chest as high as you can, while swinging your arms in a running motion. Continue lifting your knees up as high as you can, alternating between your left and right leg with each repetition. Keep the pace steady, but slow down if you need to maintain proper form. Repeat the movement for the desired number of sets. For each set do 30-45 seconds.',
        sets: 2,
        reps: 0,
        // duration: 30secs,
        musclegroup_id: 6,
        // image_id: ,
    },
    {
        exercise_name: 'Straight Leg Kick',
        description: ' Stand with your feet shoulder-width apart and your arms by your sides. Lift your left leg straight out in front of you, while keeping your knee straight. Swing your right arm forward and up to meet your left foot, while keeping your left foot flexed. Lower your left leg back down to the starting position, then repeat on the other side. Continue alternating between your left and right leg with each repetition.Repeat the movement for the desired number of sets. For each set fo 30-45 seconds.',
        sets: 2,
        reps: 0,
        musclegroup_id: 6,
        // image_id: ,
    },
    {
        exercise_name: 'Indoor Walk (Treadmill)',
        description: ' Step onto the treadmill and stand with your feet shoulder-width apart. Use the console or buttons on the treadmill to start the machine at a slow speed, such as 1 or 2 miles per hour. Begin walking on the treadmill, making sure to keep your head up and your shoulders relaxed. Swing your arms naturally at your sides, with your elbows bent at a 90-degree angle. Keep your feet pointed straight ahead and land on the balls of your feet, rolling through to your heels with each step. Gradually increase the speed of the treadmill as you become more comfortable, and aim to walk for at least 5-10 minutes per session.When youre finished, use the console or buttons to slow the treadmill down and step off the machine carefully.',
        sets: 2,
        reps: 0,
        // duration: '10 minutes',
        musclegroup_id: 7,
        // image_id: ,
    },
    {
        exercise_name: 'Foam Rollout',
        description: ' Choose a foam roller thats appropriate for your fitness level and experience, and place it on the ground. Lie down on the foam roller so that its positioned under a specific muscle group that you want to target, such as your hamstrings, quads, or back.Use your hands and feet to lift your body up off the ground, so that youre balancing on the foam roller.Slowly roll your body back and forth over the foam roller, applying gentle pressure to the targeted muscle group.Continue rolling for several minutes, paying attention to any areas that feel particularly tight or sore. When youre finished rolling a specific muscle group, move onto the next area that you want to target.Drink plenty of water before, during, and after your foam rolling session to help flush out toxins and reduce soreness.',
        sets: 2,
        reps: 0,
        musclegroup_id: 7,
        // image_id: ,
    },
    {
        exercise_name: 'Quick Stretch',
        description: ' Start by standing with your feet hip-width apart and your arms at your sides. Reach your arms up overhead, stretching your whole body upwards. Reach your right arm across your body, stretching your left shoulder. Repeat on the other side, reaching your left arm across your body. Take a wide stance and stretch your legs by reaching down toward your toes, keeping your knees straight. Stand up and cross your right ankle over your left knee, then sit down into a squat to stretch your hip. Repeat on the other side, crossing your left ankle over your right knee and sitting into the squat. Stand with your feet shoulder-width apart and clasp your hands behind your back, then raise your arms and stretch your chest.Finish with a gentle neck stretch by tilting your head to the left, then to the right, and then dropping your chin to your chest.',
        sets: 2,
        reps: 0,
        musclegroup_id: 7,
        // image_id: ,
    },
];

const seedExercises = () => Exercises.bulkCreate(exerciseData);

module.exports = seedExercises;